-- Generated by Gemini
-- nLogistic Schema

CREATE TABLE Users (
    IdUser SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Transporters (
    IdTransporter SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Transports (
    IdTransport SERIAL PRIMARY KEY,
    IdUser INT NOT NULL,
    "From" VARCHAR(255) NOT NULL,
    "To" VARCHAR(255) NOT NULL,
    Count INT NOT NULL,
    FOREIGN KEY (IdUser) REFERENCES Users(IdUser)
);

CREATE TABLE Offers (
    IdOffer SERIAL PRIMARY KEY,
    IdTransporter INT NOT NULL,
    IdTransport INT NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (IdTransporter) REFERENCES Transporters(IdTransporter),
    FOREIGN KEY (IdTransport) REFERENCES Transports(IdTransport)
);
